name: Gradle Package

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'corretto'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.ASSUME_ROLE_ARN }}
        aws-region: ${{ vars.AWS_REGION }}
        role-session-name: github-actions-session

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Create Gradle configuration
      run: |
       # Create a fresh directory
        WORKDIR=$(mktemp -d)
        chmod 700 "$WORKDIR"
        
        # Get passphrase
        aws secretsmanager get-secret-value --region us-east-1 --secret-id ${{ secrets.GPG_KEY_ID }} --query SecretString --output text | jq -r .passphrase > "$WORKDIR/passphrase.txt"
        
        # Get private key directly to a file
        aws secretsmanager get-secret-value --region us-east-1 --secret-id ${{ secrets.GPG_KEY_ID }} --query SecretString --output text | jq -r .privateKey > "$WORKDIR/private.key"
        
        # Create a temporary GPG home that won't be used by agent
        export GNUPGHOME="$WORKDIR/gpg"
        mkdir -p "$GNUPGHOME"
        chmod 700 "$GNUPGHOME"
        
        # Import key without agent
        gpg --batch --no-tty --no-use-agent \
            --passphrase-file "$WORKDIR/passphrase.txt" \
            --import "$WORKDIR/private.key"
        
        # Export directly to file without agent
        gpg --batch --no-tty --no-use-agent \
            --passphrase-file "$WORKDIR/passphrase.txt" \
            --export-secret-keys 25557E2C > "$WORKDIR/secring.gpg"
        
        # Create gradle.properties
        {
            echo "signingEnabled=true"
            echo "mavenUsername=$(aws secretsmanager get-secret-value --region us-east-1 --secret-id ${{ secrets.MAVEN_TOKEN_ID }} --query SecretString --output text | jq -r .username)"
            echo "mavenPassword=$(aws secretsmanager get-secret-value --region us-east-1 --secret-id ${{ secrets.MAVEN_TOKEN_ID }} --query SecretString --output text | jq -r .password)"
            echo "# Signing key: https://keys.openpgp.org/vks/v1/by-fingerprint/FAC40B939F532005395118AF259316AA25557E2C"
            echo "signing.keyId=25557E2C"
            echo "signing.password=$(cat "$WORKDIR/passphrase.txt")"
            echo "signing.secretKeyRingFile=$WORKDIR/secring.gpg"
        } > gradle.properties
        
        # Don't remove WORKDIR as Gradle needs it
        chmod 600 "$WORKDIR/secring.gpg"

    - name: Build with Gradle
      run: ./gradlew build
